name: lassensus
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - minimap2
  - samtools
  - ivar
  - lassaseq
  - seqtk
  - medaka
  - numpy<2.0
  - h5py~=3.10.0
  - pip
  - pip:
    - ont-mappy
    - ont-parasail 